data_dir: 'datataset/heatmap_npy'
metadata_csv_filename: dataset/annotations/test_metadata.csv
action_mapping_file: dataset/annotations/action_label_mapping.json

backbone: 'r2plus1d_18'
devices: ['cuda:0']

# released_checkpoint: 'r2plus1d_34-tsp_on_thumos14'
# local_checkpoint: ~
ckpt: r2plus1d_34-tsp_on_thumos14

clip_len: 16
frame_rate: 15
stride: 16

batch_size: 32
workers: 6

# output_dir: ./data/r2plus1d_34-tsp_on_thumos14_features/stride_16/
shard_id: 0
num_shards: 1