dataset_name: rehab
train_split: train
val_split: test
dataset: {
  csv_groundtruth: 'dataset/annotations/stride_16/{}_tsp_groundtruth_aug.csv',
  csv_metadata: 'dataset/annotations/stride_16/{}_metadata_aug.csv',
  feat_folder: dataset/TSP_featuress/stride_16,
  label_mapping_json: dataset/annotations/stride_16/action_label_mapping.json,
  ignored_list: [
    
  ],
  file_prefix: ~,
  file_ext: .pkl,
  num_classes: 2,
  input_dim: 512,
  feat_stride: 32 ,
  num_frames: 32,
  # serve as data augmentation
  trunc_thresh: 0.5,
  crop_ratio: [0.9, 1.0],
  max_seq_len: 256,
}
model: {
  fpn_type: identity,
  max_buffer_len_factor: 6.0,
  n_mha_win_size: 9,
}
opt: {
  learning_rate: 0.0001,
  epochs: 30,
  weight_decay: 0.05,
}
loader: {
  batch_size: 2,
}
train_cfg: {
  init_loss_norm: 100,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
}
# the inference on THUMOS is quite different from EPIC-kitchens
# a major performance gain is achieved by fusing external classification scores
# doing so will require disable multiclass_nms and enable score fusion
test_cfg: {
  voting_thresh: 0.7,
  pre_nms_topk: 2000,
  max_seg_num: 200,
  min_score: 0.001,
  # when using external scores, our model is generating "proposals"
  # multiclass_nms: False,
  # ext_score_file: ./data/thumos/annotations/thumos14_cls_scores.pkl,
  # comment out L47-48 and uncomment L50 to disable score fusion
  multiclass_nms: True,
}
output_folder: ActionFormer/runs/ckpt/

print_freq: 10  # print frequency
ckpt_freq: 5  # checkpoint frequency
output: ''  # name of exp folder
resume: ''  # path to a checkpoint